n = str(input('Type something: '))
print(type(n))
print(f'Are there only spaces? {n.isspace()}')
print(f"Is a number? {n.isnumeric()}")
print(f"Is alphabetic? {n.isalpha()}")
print(f"Is alphanumeric? {n.isalnum()}")
print(f'Is uppercase? {n.isupper()}')
print(f'Is lowercase? {n.islower()}')
print(f'Is captalized? {n.istitle()}')