n = float(input('Type a ditance in meters: '))
print("the measure of {n} is equivalent to")
print(f"{n/1000}km")
print(F'{n/100}hm')
print(f"{n/10}dam")
print(f"{n*10}dm")
print(f"{n*100}cm")
print(f'{n*1000}mm')